# Regenerates default_gifs.h from gifs/*.gif — the default pack embedded in
# app flash and seeded onto LittleFS on first boot (seedDefaultGifs() in
# gif_player.h). Run after adding/removing files in gifs/, then rebuild.
$fw = Split-Path $PSScriptRoot -Parent          # the firmware/ folder
$gifs = Get-ChildItem (Join-Path $fw 'gifs\*.gif') | Sort-Object Name
$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('/* AUTO-GENERATED by firmware/tools/make_default_gifs.ps1 - do not edit by hand.')
[void]$sb.AppendLine(' * DigiFrame - default GIF pack embedded in app flash; copied to LittleFS')
[void]$sb.AppendLine(' * once on first boot (marker /.gifs_seeded), then fully user-deletable. */')
[void]$sb.AppendLine('#pragma once')
[void]$sb.AppendLine('')
$entries = @()
foreach ($g in $gifs) {
  $ident = 'DG_' + ($g.BaseName -replace '[^A-Za-z0-9]', '_')
  $bytes = [System.IO.File]::ReadAllBytes($g.FullName)
  [void]$sb.AppendLine("static const uint8_t $ident[] PROGMEM = {")
  for ($i = 0; $i -lt $bytes.Length; $i += 24) {
    $end = [Math]::Min($i + 24, $bytes.Length)
    [void]$sb.AppendLine(($bytes[$i..($end - 1)] -join ',') + ',')
  }
  [void]$sb.AppendLine('};')
  $entries += "  { `"/$($g.Name)`", $ident, sizeof($ident) },"
}
[void]$sb.AppendLine('')
[void]$sb.AppendLine('struct DefaultGif { const char *path; const uint8_t *data; size_t len; };')
[void]$sb.AppendLine('static const DefaultGif DEFAULT_GIFS[] = {')
$entries | ForEach-Object { [void]$sb.AppendLine($_) }
[void]$sb.AppendLine('};')
[void]$sb.AppendLine('static const size_t DEFAULT_GIF_COUNT = sizeof(DEFAULT_GIFS) / sizeof(DEFAULT_GIFS[0]);')
$out = Join-Path $fw 'DigiFrame\default_gifs.h'
[System.IO.File]::WriteAllText($out, $sb.ToString())
"wrote {0} ({1:N0} KB, {2} gifs)" -f $out, ((Get-Item $out).Length / 1KB), $gifs.Count
